### ISSUE TITLE
vscode copilot chat  0.16.0 版本疑似接口更新，出现Authorization header is badly formatted

### ISSUE THREAD

**Issue by pennbay** [linux-do/override#35]
**现象**：更新vscode 和copilot插件后，**Copilot补全正常，但Chat插件v0.16.0 异常，将Chat插件回退到v 0.15.2可正常使用**。

**初步原因猜测**：Copilot Chat插件更新了接口，与Override v0.0.4不匹配。

PS：重试了两遍，**问题可复现**。

### 更新到新版本插件-出现异常
- vscode：v1.90.0
- github.copilot: v1.199.0
- github.copilot-chat: v 0.16.0

Copilot Chat 对话异常

``` 
2024-06-06 13:59:32.396 [info] [FetcherService] Using the Helix fetcher.
2024-06-06 13:59:32.396 [info] [gitExtensionService] Initializing Git extension service.
2024-06-06 13:59:32.396 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-06-06 13:59:32.396 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-06-06 13:59:32.396 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-06-06 13:59:32.445 [info] [auth] Logged in as xxxx
2024-06-06 13:59:33.367 [info] [chat] copilot token chat_enabled: true
2024-06-06 13:59:33.367 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-06-06 13:59:33.367 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-06-06 13:59:33.379 [info] [auth] Got Copilot token for xxxx
2024-06-06 13:59:34.726 [info] [RemoteAgents] Invalid remote agent response: bad request: Authorization header is badly formatted
 (SyntaxError: Unexpected token 'b', "bad reques"... is not valid JSON)
2024-06-06 14:00:56.558 [info] [extension] Error: Unable to resolve model with family selection: gpt-4
    at Z2.getChatModel (c:\Users\xxxx\.vscode\extensions\github.copilot-chat-0.16.0\dist\extension.js:1164:5671)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at IT.getChatEndpoint (c:\Users\xxxx\.vscode\extensions\github.copilot-chat-0.16.0\dist\extension.js:1164:7377)
    at Function.createIntentInvocation (c:\Users\xxxx\.vscode\extensions\github.copilot-chat-0.16.0\dist\extension.js:818:5585)
    at K6._provideResponseWithProgress (c:\Users\xxxx\.vscode\extensions\github.copilot-chat-0.16.0\dist\extension.js:844:553)
    at K6.provideResponseWithProgress (c:\Users\xxxx\.vscode\extensions\github.copilot-chat-0.16.0\dist\extension.js:842:8996)
    at n.z (c:\Users\xxxx\.vscode\extensions\github.copilot-chat-0.16.0\dist\extension.js:854:1972)
    at m.$invokeAgent (c:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:49553)
```

### 回退到旧版本插件-正常使用
- vscode：v1.89.1
- github.copilot: v1.199.0
- github.copilot-chat: v 0.15.2

Copilot Chat 对话正常

``` 
2024-06-06 14:08:45.453 [info] [FetcherService] Using Helix fetcher
2024-06-06 14:08:45.453 [info] [gitExtensionService] Initializing Git extension service.
2024-06-06 14:08:45.663 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-06-06 14:08:45.663 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-06-06 14:08:45.664 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-06-06 14:08:46.389 [info] [auth] Logged in as xxxx
2024-06-06 14:08:47.673 [info] [chat] copilot token chat_enabled: true
2024-06-06 14:08:47.673 [info] [chat] Registration of interactive providers failed:,Error: Extension 'GitHub.copilot-chat' CANNOT use API proposal: aiTextSearchProvider.
Its package.json#enabledApiProposals-property declares: interactive, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, chatProvider, mappedEditsProvider, aiRelatedInformation, codeActionAI, findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu, newSymbolNamesProvider, findFiles2, extensionsAny, authLearnMore, testObserver but NOT aiTextSearchProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api GitHub.copilot-chat
2024-06-06 14:08:47.673 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-06-06 14:08:47.673 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-06-06 14:08:47.684 [info] [auth] Got Copilot token for xxxx
2024-06-06 14:09:06.980 [info] [chat fetch] url http://localhost:8181/v1/chat/completions
2024-06-06 14:09:06.980 [info] [chat fetch] modelMaxPromptTokens 3072
2024-06-06 14:09:06.980 [info] [chat fetch] modelMaxResponseTokens 4096
2024-06-06 14:09:06.980 [info] [chat fetch] chat model gpt-4
2024-06-06 14:09:07.820 [info] [chat fetch] request.response: [http://localhost:8181/v1/chat/completions], took 839 ms
2024-06-06 14:09:07.830 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-06-06 14:09:07.832 [info] [streamChoices] request done: requestId: [] model deployment ID: []
2024-06-06 14:09:08.184 [info] [chat fetch] url http://localhost:8181/v1/chat/completions
2024-06-06 14:09:08.184 [info] [chat fetch] modelMaxPromptTokens 7168
2024-06-06 14:09:08.184 [info] [chat fetch] modelMaxResponseTokens 4096
2024-06-06 14:09:08.184 [info] [chat fetch] chat model gpt-3.5-turbo
2024-06-06 14:09:09.404 [info] [chat fetch] request.response: [http://localhost:8181/v1/chat/completions], took 1218 ms
2024-06-06 14:09:09.404 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-06-06 14:09:09.405 [info] [streamChoices] request done: requestId: [] model deployment ID: []
```

**Comment by wozulong** [comment]
感谢反馈，已更新。请查看新的README.md，添加设置 `"debug.overrideCAPIUrl": "http://127.0.0.1:8181",`

**Comment by pennbay** [comment]
貌似还有问题
```bash
$ docker logs override-app 
[GIN] 2024/06/06 - 08:11:57 | 200 |     160.377µs |      172.29.0.1 | GET      "/models"
[GIN] 2024/06/06 - 08:12:05 | 404 |         852ns |      172.29.0.1 | POST     "/chat/completions"
```

```
2024-06-06 08:11:56.257 [info] [FetcherService] Using the Helix fetcher.
2024-06-06 08:11:56.257 [info] [gitExtensionService] Initializing Git extension service.
2024-06-06 08:11:56.366 [info] [auth] Logged in as xxx
2024-06-06 08:11:56.378 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-06-06 08:11:56.378 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-06-06 08:11:56.378 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-06-06 08:11:56.921 [info] [chat] copilot token chat_enabled: true
2024-06-06 08:11:56.922 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-06-06 08:11:56.922 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-06-06 08:11:56.939 [info] [auth] Got Copilot token for xxxx
2024-06-06 08:11:58.612 [info] [RemoteAgents] Invalid remote agent response: bad request: Authorization header is badly formatted
 (SyntaxError: Unexpected token 'b', "bad reques"... is not valid JSON)
2024-06-06 08:12:05.124 [info] [chat fetch] request.response: [http://127.0.0.1:8181/chat/completions], took 70 ms
2024-06-06 08:12:05.125 [info] [chat fetch] Request ID for failed request: ,441a3ad1-d102-49e6-9ea4-2210b1a15ea6
2024-06-06 08:12:05.125 [info] [chat fetch] Unhandled status from server:,404,404 page not found
```

**注意到**
之前成功请求的url为`http://127.0.0.1:8181/v1/chat/completions`

但是此版本的请求url为`http://127.0.0.1:8181/chat/completions`

**Comment by wozulong** [comment]
那你改一下override的路由好了

**Comment by pennbay** [comment]
我对go基本不熟悉，尝试修改了路由为这样，chat和代码补全都正常（无鉴权）。
但我感觉鉴权那里不太对劲，也不知道该如何修改，请各位有空时修改下。

```
func (s *ProxyService) InitRoutes(e *gin.Engine) {
	e.GET("/_ping", s.pong)
	e.GET("/models", s.models)
	authToken := s.cfg.AuthToken // replace with your dynamic value as needed
	if authToken != "" {
		// 鉴权
		v1 := e.Group("/:token/", AuthMiddleware(authToken))
		{
			v1.POST("/chat/completions", s.completions)
			v1.POST("/v1/engines/copilot-codex/completions", s.codeCompletions)
		}
	} else {
		e.POST("/chat/completions", s.completions)
		e.POST("/v1/engines/copilot-codex/completions", s.codeCompletions)
	}
}
```

**Comment by xiaozhang959** [comment]
> 貌似还有问题
> 
> ```shell
> $ docker logs override-app 
> [GIN] 2024/06/06 - 08:11:57 | 200 |     160.377µs |      172.29.0.1 | GET      "/models"
> [GIN] 2024/06/06 - 08:12:05 | 404 |         852ns |      172.29.0.1 | POST     "/chat/completions"
> ```
> 
> ```
> 2024-06-06 08:11:56.257 [info] [FetcherService] Using the Helix fetcher.
> 2024-06-06 08:11:56.257 [info] [gitExtensionService] Initializing Git extension service.
> 2024-06-06 08:11:56.366 [info] [auth] Logged in as xxx
> 2024-06-06 08:11:56.378 [info] [gitExtensionService] Successfully activated the vscode.git extension.
> 2024-06-06 08:11:56.378 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
> 2024-06-06 08:11:56.378 [info] [gitExtensionService] Successfully registered Git commit message provider.
> 2024-06-06 08:11:56.921 [info] [chat] copilot token chat_enabled: true
> 2024-06-06 08:11:56.922 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
> 2024-06-06 08:11:56.922 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
> 2024-06-06 08:11:56.939 [info] [auth] Got Copilot token for xxxx
> 2024-06-06 08:11:58.612 [info] [RemoteAgents] Invalid remote agent response: bad request: Authorization header is badly formatted
>  (SyntaxError: Unexpected token 'b', "bad reques"... is not valid JSON)
> 2024-06-06 08:12:05.124 [info] [chat fetch] request.response: [http://127.0.0.1:8181/chat/completions], took 70 ms
> 2024-06-06 08:12:05.125 [info] [chat fetch] Request ID for failed request: ,441a3ad1-d102-49e6-9ea4-2210b1a15ea6
> 2024-06-06 08:12:05.125 [info] [chat fetch] Unhandled status from server:,404,404 page not found
> ```
> 
> **注意到** 之前成功请求的url为`http://127.0.0.1:8181/v1/chat/completions`
> 
> 但是此版本的请求url为`http://127.0.0.1:8181/chat/completions`

佬，你这个问题解决了吗？  
我没改始皇的文件，执行后如果"debug.overrideCAPIUrl"填了 "https://xxxx.xyz/v1",就一直报错Unable to resolve model with family selection: gpt-4，如果填了"https://xxxx.xyz"的话就跟你这个相同的问题，一直请求的是/chat/completions而不是/v1/chat/completions

**Comment by pennbay** [comment]
请修改`main.go`的`InitRoutes`函数，参照https://github.com/linux-do/override/issues/35#issuecomment-2151817328 。

**Comment by xiaozhang959** [comment]
> 请修改`main.go`的`InitRoutes`函数，参照[#35 (comment)](https://github.com/linux-do/override/issues/35#issuecomment-2151817328) 。

可以了可以了，感谢佬

**Comment by rqi14** [comment]
> func (s *ProxyService) InitRoutes(e *gin.Engine) {
> 	e.GET("/_ping", s.pong)
> 	e.GET("/models", s.models)
> 	authToken := s.cfg.AuthToken // replace with your dynamic value as needed
> 	if authToken != "" {
> 		// 鉴权
> 		v1 := e.Group("/:token/", AuthMiddleware(authToken))
> 		{
> 			v1.POST("/chat/completions", s.completions)
> 			v1.POST("/v1/engines/copilot-codex/completions", s.codeCompletions)
> 		}
> 	} else {
> 		e.POST("/chat/completions", s.completions)
> 		e.POST("/v1/engines/copilot-codex/completions", s.codeCompletions)
> 	}
> }

clone repo之后我也遇到了一样的问题。请问这个修改是否没有被合并呢？
