### ISSUE TITLE
vscode copilot chat 更新到0.20.0后 chat 无法使用

### ISSUE THREAD

**Issue by pennbay** [linux-do/override#55]
今天 vscode将copilot chat插件更新到了0.20.0，导致override后端的chat 无法使用，但补全可正常使用。

## 报错信息
```
2024-09-09 07:25:05.913 [info] Using the Electron fetcher.
2024-09-09 07:25:05.913 [info] Initializing Git extension service.
2024-09-09 07:25:05.913 [info] Successfully activated the vscode.git extension.
2024-09-09 07:25:05.913 [info] Enablement state of the vscode.git extension: true.
2024-09-09 07:25:05.913 [info] Successfully registered Git commit message provider.
2024-09-09 07:25:06.530 [info] Logged in as xx
2024-09-09 07:25:07.549 [info] Got Copilot token for xx
2024-09-09 07:25:07.551 [info] Not registering default platform agent because user is not on an enterprise plan.
2024-09-09 07:25:07.558 [info] copilot token chat_enabled: true, sku: yearly_subscriber
2024-09-09 07:25:07.558 [info] GitHub.vscode-pull-request-github extension is not yet activated.
2024-09-09 07:25:07.566 [info] Fetched model metadata in 15ms d70f2471-0f35-461f-86ee-9cca46ca2663
2024-09-09 07:25:07.567 [warning] Invalid remote agent response: 404 page not found (SyntaxError: Unexpected non-whitespace character after JSON at position 4 (line 1 column 5))
2024-09-09 07:25:07.632 [info] activationBlocker from 'languageModelAccess' took for 607ms
2024-09-09 07:25:31.570 [error] Error: Unable to resolve chat model with family selection: gpt-4
    at Ah.getChatModel (/home/xx/.vscode/extensions/github.copilot-chat-0.20.0/dist/extension.js:1507:20830)
    at pR.getChatEndpoint (/home/xx/.vscode/extensions/github.copilot-chat-0.20.0/dist/extension.js:1507:24962)
    at ba.invoke (/home/xx/.vscode/extensions/github.copilot-chat-0.20.0/dist/extension.js:319:22560)
    at nI._provideResponseWithProgress (/home/xx/.vscode/extensions/github.copilot-chat-0.20.0/dist/extension.js:328:6238)
    at nI.getResult (/home/xx/.vscode/extensions/github.copilot-chat-0.20.0/dist/extension.js:328:4084)
    at t.y (/home/xx/.vscode/extensions/github.copilot-chat-0.20.0/dist/extension.js:1507:1830)
    at a.$invokeAgent (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:161:53770)
2024-09-09 07:25:34.958 [info] message 0 returned. finish reason: [stop]
2024-09-09 07:25:34.958 [info] request done: requestId: [] model deployment ID: []

```

**Comment by zhuiyue132** [comment]
+1

**Comment by pennbay** [comment]
Fixes #54 

更新至  v0.0.7后问题已解决。
https://github.com/linux-do/override/releases/tag/v0.0.7
